import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';
import { API_BASE_URL } from '../config';
import { ShieldAlert, CheckCircle2, RefreshCw, ExternalLink } from 'lucide-react';
import { formatISTDate } from '../utils/dateUtils';


export default function Alerts() {
  const [alerts, setAlerts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<'all' | 'unresolved' | 'resolved'>('all');

  const fetchAlerts = async () => {
    setLoading(true);
    try {
      const url = `${API_BASE_URL}/alerts${filter !== 'all' ? `?status=${filter}` : ''}`;
      const res = await axios.get(url);
      const data = res.data;
      setAlerts(Array.isArray(data) ? data : (Array.isArray(data?.alerts) ? data.alerts : (Array.isArray(data?.items) ? data.items : [])));
    } catch (err) {
      console.error('Failed to fetch alerts:', err);
      setAlerts([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAlerts();
  }, [filter]);

  const handleResolve = async (alertId: string) => {
    try {
      await axios.patch(`${API_BASE_URL}/alerts/${alertId}/resolve`, {
        notes: 'Resolved by analyst'
      });
      fetchAlerts();
    } catch (err) {
      alert('Failed to resolve alert');
    }
  };

  return (
    <div className="space-[#1e293b] space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold flex items-center gap-3">
            <ShieldAlert className="text-red-500" size={32} />
            Fraud Risk Alerts
          </h1>
          <p className="text-slate-500 text-sm mt-1">Real-time alerts generated by the Hybrid Quantum-Classical Risk Engine.</p>
        </div>

        <div className="flex items-center gap-2">
          <div className="inline-flex bg-slate-100 dark:bg-slate-800 p-1 rounded-lg border border-slate-200 dark:border-slate-700">
            <button
              onClick={() => setFilter('all')}
              className={`px-3 py-1.5 text-xs font-medium rounded-md transition ${filter === 'all' ? 'bg-white dark:bg-slate-700 shadow-sm text-slate-900 dark:text-white' : 'text-slate-500 hover:text-slate-900 dark:hover:text-white'}`}
            >
              All
            </button>
            <button
              onClick={() => setFilter('unresolved')}
              className={`px-3 py-1.5 text-xs font-medium rounded-md transition ${filter === 'unresolved' ? 'bg-white dark:bg-slate-700 shadow-sm text-slate-900 dark:text-white' : 'text-slate-500 hover:text-slate-900 dark:hover:text-white'}`}
            >
              Unresolved
            </button>
            <button
              onClick={() => setFilter('resolved')}
              className={`px-3 py-1.5 text-xs font-medium rounded-md transition ${filter === 'resolved' ? 'bg-white dark:bg-slate-700 shadow-sm text-slate-900 dark:text-white' : 'text-slate-500 hover:text-slate-900 dark:hover:text-white'}`}
            >
              Resolved
            </button>
          </div>

          <button
            onClick={fetchAlerts}
            className="p-2 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 rounded-lg text-slate-600 dark:text-slate-300 transition"
          >
            <RefreshCw size={16} className={loading ? 'animate-spin' : ''} />
          </button>
        </div>
      </div>

      {loading ? (
        <div className="p-12 text-center text-slate-500 bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800">
          Loading active alerts...
        </div>
      ) : alerts.length === 0 ? (
        <div className="p-12 text-center bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800">
          <CheckCircle2 className="mx-auto mb-3 text-emerald-500" size={40} />
          <h3 className="text-lg font-semibold mb-1">No Alerts Found</h3>
          <p className="text-slate-500 text-sm max-w-md mx-auto">
            All system transactions are currently within safe risk thresholds or no high-risk fraud alerts have been triggered.
          </p>
        </div>
      ) : (
        <div className="bg-white dark:bg-slate-900 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead className="bg-slate-50 dark:bg-slate-800/50 text-slate-500 border-b border-slate-200 dark:border-slate-800 uppercase text-xs">
                <tr>
                  <th className="px-6 py-4">Alert ID</th>
                  <th className="px-6 py-4">Transaction ID</th>
                  <th className="px-6 py-4">Severity</th>
                  <th className="px-6 py-4">Trigger Reason</th>
                  <th className="px-6 py-4">Timestamp</th>
                  <th className="px-6 py-4">Status</th>
                  <th className="px-6 py-4 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 dark:divide-slate-800">
                {(Array.isArray(alerts) ? alerts : []).map((a) => (
                  <tr key={a.alert_id} className="hover:bg-slate-50/50 dark:hover:bg-slate-800/30 transition">
                    <td className="px-6 py-4 font-mono text-xs font-medium text-slate-700 dark:text-slate-300">
                      {a.alert_id.slice(0, 8)}...
                    </td>
                    <td className="px-6 py-4 font-mono text-xs text-indigo-600 dark:text-indigo-400">
                      {a.transaction_id ? (
                        <Link to={`/transactions/${a.transaction_id}`} className="hover:underline inline-flex items-center gap-1">
                          {a.transaction_id.slice(0, 8)}... <ExternalLink size={12} />
                        </Link>
                      ) : (
                        'N/A'
                      )}
                    </td>
                    <td className="px-6 py-4">
                      <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-bold bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400 border border-red-200 dark:border-red-800">
                        {a.severity || 'ALERT'}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-slate-700 dark:text-slate-300 max-w-xs truncate">
                      {a.alert_reason}
                    </td>
                    <td className="px-6 py-4 text-slate-500 text-xs font-mono">
                      {formatISTDate(a.created_at)}
                    </td>
                    <td className="px-6 py-4">
                      {a.resolved ? (
                        <span className="inline-flex items-center gap-1 text-xs text-emerald-600 dark:text-emerald-400 font-medium">
                          <CheckCircle2 size={14} /> Resolved
                        </span>
                      ) : (
                        <span className="inline-flex items-center text-xs text-amber-600 dark:text-amber-400 font-medium">
                          Active
                        </span>
                      )}
                    </td>
                    <td className="px-6 py-4 text-right">
                      {!a.resolved && (
                        <button
                          onClick={() => handleResolve(a.alert_id)}
                          className="px-3 py-1 bg-emerald-50 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400 hover:bg-emerald-100 dark:hover:bg-emerald-900/50 rounded-lg text-xs font-semibold transition"
                        >
                          Resolve
                        </button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
